/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package programa;

import java.applet.AudioClip;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author davilucas
 */
public class LetroMania extends javax.swing.JFrame {
        private AudioClip musica;
        
        @Override
        protected void finalize() {
            try {
                System.gc();
            } finally {
                try {
                    super.finalize();
                } catch (Throwable ex) {
                    Logger.getLogger(LetroMania.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    /**
     * Creates new form Inicio
     */
    
    public LetroMania() {
        initComponents();
         setResizable(false);
    setLocationRelativeTo(null);
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        setFocusableWindowState(false);
        setMinimumSize(new java.awt.Dimension(419, 539));
        setPreferredSize(new java.awt.Dimension(419, 539));
        setResizable(false);
        setSize(new java.awt.Dimension(419, 539));
        getContentPane().setLayout(null);

        jButton1.setText("Muito Facil");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(150, 180, 120, 23);

        jButton2.setText("Facil");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(150, 220, 120, 23);

        jButton3.setText("Médio");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(150, 260, 120, 23);

        jButton8.setText("Desenvolvedores");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(130, 440, 170, 30);

        jButton7.setText("Como Jogar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(140, 380, 150, 30);

        jButton5.setText("Dificil");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(150, 300, 120, 23);

        jLabel3.setText("Ver: 0.8.5");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(330, 480, 70, 14);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Selecione uma Dificuldade: ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 120, 210, 70);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Sobre:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 340, 80, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/TelaPrincipal1.png"))); // NOI18N
        jLabel4.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel4AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, -8, 430, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        new NivelMuitoFacil().setVisible(true);
        getMusica().stop();
        dispose();
        System.gc();
        //Thread.currentThread().stop();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        new NivelFacil().setVisible(true);
        getMusica().stop();
        dispose();
        System.gc();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        new ComoJogar().setVisible(true);
        getMusica().stop();
        dispose();
        System.gc();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jLabel4AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel4AncestorAdded
        setMusica(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/MusicaTemaLetromania.wav")));
        getMusica().loop();
    }//GEN-LAST:event_jLabel4AncestorAdded

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
         new Desenvolvedores().setVisible(true);
         dispose();
         System.gc();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new NivelMedio().setVisible(true);
        getMusica().stop();
        dispose();
        System.gc();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new NivelDificil().setVisible(true);
        getMusica().stop();
        dispose();
        System.gc();
    }//GEN-LAST:event_jButton5ActionPerformed

    
        
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LetroMania.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LetroMania.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LetroMania.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LetroMania.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new LetroMania().setVisible(true);
                
                 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the musica
     */
    public AudioClip getMusica() {
        return musica;
    }

    /**
     * @param musica the musica to set
     */
    public void setMusica(AudioClip musica) {
        this.musica = musica;
    }

    /**
     * @return the jButton1
     */
    public javax.swing.JButton getjButton1() {
        return jButton1;
    }

    /**
     * @param jButton1 the jButton1 to set
     */
    public void setjButton1(javax.swing.JButton jButton1) {
        this.jButton1 = jButton1;
    }

    /**
     * @return the jButton2
     */
    public javax.swing.JButton getjButton2() {
        return jButton2;
    }

    /**
     * @param jButton2 the jButton2 to set
     */
    public void setjButton2(javax.swing.JButton jButton2) {
        this.jButton2 = jButton2;
    }

    /**
     * @return the jButton3
     */
    public javax.swing.JButton getjButton3() {
        return jButton3;
    }

    /**
     * @param jButton3 the jButton3 to set
     */
    public void setjButton3(javax.swing.JButton jButton3) {
        this.jButton3 = jButton3;
    }

    /**
     * @return the jButton4
     */
//    public javax.swing.JButton getjButton4() {
//        return jButton4;
//    }

    /**
     * @param jButton4 the jButton4 to set
     */
//    public void setjButton4(javax.swing.JButton jButton4) {
//        this.jButton4 = jButton4;
//    }

    /**
     * @return the jButton5
     */
    public javax.swing.JButton getjButton5() {
        return jButton5;
    }

    /**
     * @param jButton5 the jButton5 to set
     */
    public void setjButton5(javax.swing.JButton jButton5) {
        this.jButton5 = jButton5;
    }

    /**
     * @return the jButton6
     */
//    public javax.swing.JButton getjButton6() {
//        return jButton6;
//    }
//
//    /**
//     * @param jButton6 the jButton6 to set
//     */
//    public void setjButton6(javax.swing.JButton jButton6) {
//        this.jButton6 = jButton6;
//    }

    /**
     * @return the jButton7
     */
    public javax.swing.JButton getjButton7() {
        return jButton7;
    }

    /**
     * @param jButton7 the jButton7 to set
     */
    public void setjButton7(javax.swing.JButton jButton7) {
        this.jButton7 = jButton7;
    }

    /**
     * @return the jButton8
     */
    public javax.swing.JButton getjButton8() {
        return jButton8;
    }

    /**
     * @param jButton8 the jButton8 to set
     */
    public void setjButton8(javax.swing.JButton jButton8) {
        this.jButton8 = jButton8;
    }

    
   // protected void finalize() throw throwable {
    
//}
    
}
