/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package programa;

import java.applet.AudioClip;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author davilucas
 */
public class NivelMuitoFacil extends javax.swing.JFrame {

    private AudioClip musica;
    private AudioClip acertou;
    private AudioClip errou;
    private AudioClip niveis;
    
    @Override
    protected void finalize() throws Throwable {
        try {
            System.gc();
        } finally {
            super.finalize();
        }
}
    
    /**
     * Creates new form NivelMuitoFacil
     */
    public NivelMuitoFacil() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(784, 543));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel1.setText("saac");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 60, 116, 30);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(140, 60, 57, 26);

        jButton1.setText("Verificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(210, 60, 96, 29);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel6.setText("aocc");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 130, 110, 20);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(140, 130, 57, 26);

        jLabel3.setFont(new java.awt.Font("Mistral", 1, 18)); // NOI18N
        jLabel3.setText("0");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(280, 20, 40, 20);

        jLabel5.setFont(new java.awt.Font("Mistral", 1, 18)); // NOI18N
        jLabel5.setText("0");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(680, 10, 40, 50);

        jButton2.setText("Verificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(210, 130, 96, 29);

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel7.setText("dadei");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 190, 110, 20);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(140, 190, 56, 26);

        jButton3.setText("Verificar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(210, 190, 96, 29);

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel8.setText("mcaa");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 250, 110, 20);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(140, 250, 56, 26);

        jButton4.setText("Verificar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(210, 250, 96, 29);

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel9.setText("avle");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 310, 110, 20);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(140, 310, 56, 26);

        jButton5.setText("Verificar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(210, 310, 96, 29);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/BorrachaFinal.png"))); // NOI18N
        jButton6.setText("Desistir");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(60, 430, 170, 70);

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel11.setText("mrao");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(430, 60, 110, 20);

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel12.setText("ivad");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(430, 130, 110, 20);

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel13.setText("emod");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(430, 190, 110, 20);

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel14.setText("ebsa");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(430, 250, 110, 20);

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel15.setText("rtea");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(430, 310, 110, 20);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(530, 60, 60, 26);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(530, 130, 60, 26);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(530, 190, 60, 26);
        getContentPane().add(jTextField9);
        jTextField9.setBounds(530, 250, 60, 26);
        getContentPane().add(jTextField10);
        jTextField10.setBounds(530, 310, 60, 26);

        jButton7.setText("Verificar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(600, 60, 96, 29);

        jButton8.setText("Verificar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(600, 130, 96, 29);

        jButton9.setText("Verificar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(600, 190, 96, 29);

        jButton10.setText("Verificar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(600, 250, 96, 29);

        jButton11.setText("Verificar");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(600, 310, 96, 29);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/NiveisFinal.gif"))); // NOI18N
        jLabel16.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel16AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(jLabel16);
        jLabel16.setBounds(0, 0, 790, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nome1 = "casa";
        String nome2 = jTextField1.getText();
        int a = Integer.parseInt(jLabel3.getText()), s, s2, b = Integer.parseInt(jLabel5.getText());

        if (nome1.equals(nome2)) {

            jLabel1.setText("correto!");

            setAcertou(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/SomDeAcerto.wav")));
            getAcertou().play();

            s = a + 1;
            jLabel3.setText(Integer.toString(s));

            jButton1.setEnabled(false); // para desabilitar um botao.

            if (a == 9) {

                new VoceGanhou().setVisible(true);
                dispose(); //para fechar uma janela e abrir outra.
                getNiveis().stop();
            }
        } else {

            setErrou(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/SomDeErro.wav")));
            getErrou().play();

            s2 = b + 1;

            if (b == 9) {

                new VocePerdeu().setVisible(true);
                dispose(); //para fechar uma janela e abrir outra.
                getNiveis().stop();
            } else {

                jLabel5.setText(Integer.toString(s2));

            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String nome1 = "caco";
        String nome2 = jTextField2.getText();
        int a = Integer.parseInt(jLabel3.getText()), s, s2, b = Integer.parseInt(jLabel5.getText());

        if (nome1.equals(nome2)) {

            jLabel6.setText("correto!");

            setAcertou(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/SomDeAcerto.wav")));
            getAcertou().play();

            s = a + 1;
            jLabel3.setText(Integer.toString(s));

            jButton2.setEnabled(false); // para desabilitar um botao.

            if (a == 9) {

                new VoceGanhou().setVisible(true);
                dispose(); //para fechar uma janela e abrir outra.
                getNiveis().stop();
            }
        } else {

            setErrou(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/SomDeErro.wav")));
            getErrou().play();

            s2 = b + 1;

            if (b == 9) {

                new VocePerdeu().setVisible(true);
                dispose(); //para fechar uma janela e abrir outra.
                getNiveis().stop();
                
            } else {

                jLabel5.setText(Integer.toString(s2));

            }

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String nome1 = "idade";
        String nome2 = jTextField3.getText();
        int a = Integer.parseInt(jLabel3.getText()), s, s2, b = Integer.parseInt(jLabel5.getText());

        if (nome1.equals(nome2)) {

            jLabel7.setText("correto!");

            setAcertou(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/SomDeAcerto.wav")));
            getAcertou().play();

            s = a + 1;
            jLabel3.setText(Integer.toString(s));

            jButton3.setEnabled(false); // para desabilitar um botao.

            if (a == 9) {

                new VoceGanhou().setVisible(true);
                dispose(); //para fechar uma janela e abrir outra.
                getNiveis().stop();
                
            }
        } else {

            setErrou(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/SomDeErro.wav")));
            getErrou().play();

            s2 = b + 1;

            if (b == 9) {

                new VocePerdeu().setVisible(true);
                dispose(); //para fechar uma janela e abrir outra.
                getNiveis().stop();
                
            } else {

                jLabel5.setText(Integer.toString(s2));

            }

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String nome1 = "cama";
        String nome2 = jTextField4.getText();
        int a = Integer.parseInt(jLabel3.getText()), s, s2, b = Integer.parseInt(jLabel5.getText());

        if (nome1.equals(nome2)) {

            jLabel8.setText("correto!");

            setAcertou(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/SomDeAcerto.wav")));
            getAcertou().play();

            s = a + 1;
            jLabel3.setText(Integer.toString(s));

            jButton4.setEnabled(false); // para desabilitar um botao.

            if (a == 9) {

                new VoceGanhou().setVisible(true);
                dispose(); //para fechar uma janela e abrir outra.
                getNiveis().stop();
                
            }
        } else {

            setErrou(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/SomDeErro.wav")));
            getErrou().play();

            s2 = b + 1;

            if (b == 9) {

                new VocePerdeu().setVisible(true);
                dispose(); //para fechar uma janela e abrir outra.
                getNiveis().stop();
                
            } else {

                jLabel5.setText(Integer.toString(s2));

            }

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String nome1 = "vela";
        String nome2 = jTextField5.getText();
        int a = Integer.parseInt(jLabel3.getText()), s, s2, b = Integer.parseInt(jLabel5.getText());

        if (nome1.equals(nome2)) {

            jLabel9.setText("correto!");

            setAcertou(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/SomDeAcerto.wav")));
            getAcertou().play();

            s = a + 1;
            jLabel3.setText(Integer.toString(s));

            jButton5.setEnabled(false); // para desabilitar um botao.

            if (a == 9) {

                new VoceGanhou().setVisible(true);
                dispose(); //para fechar uma janela e abrir outra.
                getNiveis().stop();
                
            }
        } else {

            setErrou(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/SomDeErro.wav")));
            getErrou().play();

            s2 = b + 1;

            if (b == 9) {

                new VocePerdeu().setVisible(true);
                dispose(); //para fechar uma janela e abrir outra.
                getNiveis().stop();
                
            } else {

                jLabel5.setText(Integer.toString(s2));

            }

        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        new LetroMania().setVisible(true);
        dispose();
        getNiveis().stop();
        System.gc();

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String nome1 = "amor";
        String nome2 = jTextField6.getText();
        int a = Integer.parseInt(jLabel3.getText()), s, s2, b = Integer.parseInt(jLabel5.getText());

        if (nome1.equals(nome2)) {

            jLabel11.setText("correto!");

            setAcertou(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/SomDeAcerto.wav")));
            getAcertou().play();

            s = a + 1;
            jLabel3.setText(Integer.toString(s));

            jButton7.setEnabled(false); // para desabilitar um botao.

            if (a == 9) {

                new VoceGanhou().setVisible(true);
                dispose(); //para fechar uma janela e abrir outra.
                getNiveis().stop();
                
            }
        } else {

            setErrou(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/SomDeErro.wav")));
            getErrou().play();

            s2 = b + 1;

            if (b == 9) {

                new VocePerdeu().setVisible(true);
                dispose(); //para fechar uma janela e abrir outra.
                getNiveis().stop();
                
            } else {

                jLabel5.setText(Integer.toString(s2));

            }

        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String nome1 = "vida";
        String nome2 = jTextField7.getText();
        int a = Integer.parseInt(jLabel3.getText()), s, s2, b = Integer.parseInt(jLabel5.getText());

        if (nome1.equals(nome2)) {

            jLabel12.setText("correto!");

            setAcertou(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/SomDeAcerto.wav")));
            getAcertou().play();

            s = a + 1;
            jLabel3.setText(Integer.toString(s));

            jButton8.setEnabled(false); // para desabilitar um botao.

            if (a == 9) {

                new VoceGanhou().setVisible(true);
                dispose(); //para fechar uma janela e abrir outra.
                getNiveis().stop();
                
            }
        } else {

            setErrou(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/SomDeErro.wav")));
            getErrou().play();

            s2 = b + 1;

            if (b == 9) {

                new VocePerdeu().setVisible(true);
                dispose(); //para fechar uma janela e abrir outra.
                getNiveis().stop();
                
            } else {

                jLabel5.setText(Integer.toString(s2));

            }

        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String nome1 = "medo";
        String nome2 = jTextField8.getText();
        int a = Integer.parseInt(jLabel3.getText()), s, s2, b = Integer.parseInt(jLabel5.getText());

        if (nome1.equals(nome2)) {

            jLabel13.setText("correto!");

            setAcertou(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/SomDeAcerto.wav")));
            getAcertou().play();

            s = a + 1;
            jLabel3.setText(Integer.toString(s));

            jButton9.setEnabled(false); // para desabilitar um botao.

            if (a == 9) {

                new VoceGanhou().setVisible(true);
                dispose(); //para fechar uma janela e abrir outra.
                getNiveis().stop();
                
            }
        } else {

            setErrou(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/SomDeErro.wav")));
            getErrou().play();

            s2 = b + 1;

            if (b == 9) {

                new VocePerdeu().setVisible(true);
                dispose(); //para fechar uma janela e abrir outra.
                getNiveis().stop();
                
            } else {

                jLabel5.setText(Integer.toString(s2));

            }

        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        String nome1 = "base";
        String nome2 = jTextField9.getText();
        int a = Integer.parseInt(jLabel3.getText()), s, s2, b = Integer.parseInt(jLabel5.getText());

        if (nome1.equals(nome2)) {

            jLabel14.setText("correto!");

            setAcertou(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/SomDeAcerto.wav")));
            getAcertou().play();

            s = a + 1;
            jLabel3.setText(Integer.toString(s));

            jButton10.setEnabled(false); // para desabilitar um botao.

            if (a == 9) {

                setMusica(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/MusicaNiveis.wav")));
                getMusica().stop();

                new VoceGanhou().setVisible(true);
                dispose(); //para fechar uma janela e abrir outra.
                getNiveis().stop();
                
            }
        } else {

            setErrou(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/SomDeErro.wav")));
            getErrou().play();

            s2 = b + 1;

            if (b == 9) {

                new VocePerdeu().setVisible(true);
                dispose(); //para fechar uma janela e abrir outra.
                getNiveis().stop();
                
            } else {

                jLabel5.setText(Integer.toString(s2));

            }

        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        String nome1 = "reta";
        String nome2 = jTextField10.getText();
        int a = Integer.parseInt(jLabel3.getText()), s, s2, b = Integer.parseInt(jLabel5.getText());

        if (nome1.equals(nome2)) {

            jLabel15.setText("correto!");

            setAcertou(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/SomDeAcerto.wav")));
            getAcertou().play();

            s = a + 1;
            jLabel3.setText(Integer.toString(s));

            jButton11.setEnabled(false); // para desabilitar um botao.

            if (a == 9) {

                new VoceGanhou().setVisible(true);
                dispose(); //para fechar uma janela e abrir outra.
                getNiveis().stop();
                
            }
        } else {

            setErrou(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/SomDeErro.wav")));
            getErrou().play();

            s2 = b + 1;

            if (b == 9) {

                new VocePerdeu().setVisible(true);
                dispose(); //para fechar uma janela e abrir outra.
                getNiveis().stop();
                
            } else {

                jLabel5.setText(Integer.toString(s2));

            }

        }

    }//GEN-LAST:event_jButton11ActionPerformed

    private void jLabel16AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel16AncestorAdded

        setNiveis(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/MusicaNiveis.wav")));
        getNiveis().loop();
    }//GEN-LAST:event_jLabel16AncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NivelMuitoFacil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NivelMuitoFacil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NivelMuitoFacil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NivelMuitoFacil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NivelMuitoFacil().setVisible(true);
                    
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the musica
     */
    public AudioClip getMusica() {
        return musica;
    }

    /**
     * @param musica the musica to set
     */
    public void setMusica(AudioClip musica) {
        this.musica = musica;
    }

    /**
     * @return the acertou
     */
    public AudioClip getAcertou() {
        return acertou;
    }

    /**
     * @param acertou the acertou to set
     */
    public void setAcertou(AudioClip acertou) {
        this.acertou = acertou;
    }

    /**
     * @return the errou
     */
    public AudioClip getErrou() {
        return errou;
    }

    /**
     * @param errou the errou to set
     */
    public void setErrou(AudioClip errou) {
        this.errou = errou;
    }

    /**
     * @return the niveis
     */
    public AudioClip getNiveis() {
        return niveis;
    }

    /**
     * @param niveis the niveis to set
     */
    public void setNiveis(AudioClip niveis) {
        this.niveis = niveis;
    }

}

