/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package programa;

import java.applet.AudioClip;

/**
 *
 * @author davilucas
 */
public class NivelMedio extends javax.swing.JFrame {
    private AudioClip Acertou;
    private AudioClip Errou;
    private AudioClip Niveis;
    
    /**
     * Creates new form NivelMedio
     */
    public NivelMedio() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        setMinimumSize(new java.awt.Dimension(784, 543));
        setPreferredSize(new java.awt.Dimension(784, 543));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel1.setText("baanca");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 70, 110, 20);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel2.setText("catare");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 130, 110, 20);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel3.setText("socail");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 190, 100, 20);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel4.setText("insona");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 260, 110, 20);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel5.setText("legdoa");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 320, 110, 20);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel6.setText("boeesn");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(440, 70, 120, 20);

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel7.setText("cedenot");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(440, 130, 120, 20);

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel8.setText("eécpsie");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(440, 190, 120, 20);

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel9.setText("seuscso");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(440, 260, 110, 20);

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel10.setText("vieurdt");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(440, 320, 120, 20);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(140, 70, 80, 26);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(140, 130, 80, 26);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(140, 190, 80, 26);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(140, 260, 80, 26);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(140, 320, 80, 26);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(540, 70, 80, 26);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(540, 130, 80, 26);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(540, 190, 80, 26);
        getContentPane().add(jTextField9);
        jTextField9.setBounds(540, 260, 80, 26);
        getContentPane().add(jTextField10);
        jTextField10.setBounds(540, 320, 80, 26);

        jButton1.setText("Verificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(240, 70, 96, 29);

        jButton2.setText("Verificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(240, 130, 96, 29);

        jButton3.setText("Verificar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(240, 190, 96, 29);

        jButton4.setText("Verificar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(240, 260, 96, 29);

        jButton5.setText("Verificar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(240, 320, 96, 29);

        jButton6.setText("Verificar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(640, 70, 96, 29);

        jButton7.setText("Verificar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(640, 130, 96, 29);

        jButton8.setText("Verificar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(640, 190, 96, 29);

        jButton9.setText("Verificar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(640, 260, 96, 30);

        jButton10.setText("Verificar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(640, 320, 96, 29);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/BorrachaFinal.png"))); // NOI18N
        jButton11.setText("jButton11");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(40, 440, 170, 60);

        jLabel11.setFont(new java.awt.Font("Mistral", 1, 18)); // NOI18N
        jLabel11.setText("0");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(680, 20, 50, 30);

        jLabel12.setFont(new java.awt.Font("Mistral", 1, 18)); // NOI18N
        jLabel12.setText("0");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(280, 10, 50, 40);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/NiveisFinal.gif"))); // NOI18N
        jLabel13.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel13AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, -30, 800, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nome1 = "bacana";
        String nome2 = jTextField1.getText();
        int a = Integer.parseInt(jLabel12.getText()),s,s2,b = Integer.parseInt(jLabel11.getText());
        
        
        
        if(nome1.equals(nome2)){
         
            jLabel1.setText("correto!");
        
            setAcertou(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/SomDeAcerto.wav")));
            getAcertou().play();
            
         s = a+1;
         jLabel12.setText(Integer.toString(s));       
            
         jButton1.setEnabled( false ); // para desabilitar um botao.
        
         if(a==9){
             
               new VoceGanhou().setVisible(true); 
               dispose(); //para fechar uma janela e abrir outra.
                getNiveis().stop();
         }
         }
        
        else{
            
            setErrou(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/SomDeErro.wav")));
            getErrou().play();
            
           s2 = b+1;
         
           if(b==9){
             
               new VocePerdeu().setVisible(true); 
               dispose(); //para fechar uma janela e abrir outra
                getNiveis().stop();
           } 
           
           else{
               
               jLabel11.setText(Integer.toString(s2)); 
               
           } 
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String nome1 = "careta";
        String nome2 = jTextField2.getText();
        int a = Integer.parseInt(jLabel12.getText()),s,s2,b = Integer.parseInt(jLabel11.getText());
        
        
        
        if(nome1.equals(nome2)){
         
            jLabel2.setText("correto!");
        
            setAcertou(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/SomDeAcerto.wav")));
            getAcertou().play();
            
         s = a+1;
         jLabel12.setText(Integer.toString(s));       
            
         jButton2.setEnabled( false ); // para desabilitar um botao.
        
         if(a==9){
             
               new VoceGanhou().setVisible(true); 
               dispose(); //para fechar uma janela e abrir outra.
                getNiveis().stop();
         }
         }
        
        else{
            
            setErrou(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/SomDeErro.wav")));
            getErrou().play();
            
           s2 = b+1;
         
           if(b==9){
             
               new VocePerdeu().setVisible(true); 
               dispose(); //para fechar uma janela e abrir outra
                getNiveis().stop();
           } 
           
           else{
               
               jLabel11.setText(Integer.toString(s2)); 
               
           } 
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String nome1 = "social";
        String nome2 = jTextField3.getText();
        int a = Integer.parseInt(jLabel12.getText()),s,s2,b = Integer.parseInt(jLabel11.getText());
        
        
        
        if(nome1.equals(nome2)){
         
            jLabel3.setText("correto!");
        
            setAcertou(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/SomDeAcerto.wav")));
            getAcertou().play();
            
         s = a+1;
         jLabel12.setText(Integer.toString(s));       
            
         jButton3.setEnabled( false ); // para desabilitar um botao.
        
         if(a==9){
             
               new VoceGanhou().setVisible(true); 
               dispose(); //para fechar uma janela e abrir outra.
                getNiveis().stop();
         }
         }
        
        else{
            
            setErrou(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/SomDeErro.wav")));
            getErrou().play();
            
           s2 = b+1;
         
           if(b==9){
             
               new VocePerdeu().setVisible(true); 
               dispose(); //para fechar uma janela e abrir outra
                getNiveis().stop();
           } 
           
           else{
               
               jLabel11.setText(Integer.toString(s2)); 
               
           } 
            
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String nome1 = "insano";
        String nome2 = jTextField4.getText();
        int a = Integer.parseInt(jLabel12.getText()),s,s2,b = Integer.parseInt(jLabel11.getText());
        
        
        
        if(nome1.equals(nome2)){
         
            jLabel4.setText("correto!");
        
            setAcertou(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/SomDeAcerto.wav")));
            getAcertou().play();
            
         s = a+1;
         jLabel12.setText(Integer.toString(s));       
            
         jButton4.setEnabled( false ); // para desabilitar um botao.
        
         if(a==9){
             
               new VoceGanhou().setVisible(true); 
               dispose(); //para fechar uma janela e abrir outra.
                getNiveis().stop();
         }
         }
        
        else{
            
            setErrou(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/SomDeErro.wav")));
            getErrou().play();
            
           s2 = b+1;
         
           if(b==9){
             
               new VocePerdeu().setVisible(true); 
               dispose(); //para fechar uma janela e abrir outra
                getNiveis().stop();
           } 
           
           else{
               
               jLabel11.setText(Integer.toString(s2)); 
               
           } 
            
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String nome1 = "legado";
        String nome2 = jTextField5.getText();
        int a = Integer.parseInt(jLabel12.getText()),s,s2,b = Integer.parseInt(jLabel11.getText());
        
        
        
        if(nome1.equals(nome2)){
         
            jLabel5.setText("correto!");
        
            setAcertou(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/SomDeAcerto.wav")));
            getAcertou().play();
            
         s = a+1;
         jLabel12.setText(Integer.toString(s));       
            
         jButton5.setEnabled( false ); // para desabilitar um botao.
        
         if(a==9){
             
               new VoceGanhou().setVisible(true); 
               dispose(); //para fechar uma janela e abrir outra.
                getNiveis().stop();
         }
         }
        
        else{
            
            setErrou(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/SomDeErro.wav")));
            getErrou().play();
            
           s2 = b+1;
         
           if(b==9){
             
               new VocePerdeu().setVisible(true); 
               dispose(); //para fechar uma janela e abrir outra
                getNiveis().stop();
           } 
           
           else{
               
               jLabel11.setText(Integer.toString(s2)); 
               
           } 
            
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String nome1 = "esnobe";
        String nome2 = jTextField6.getText();
        int a = Integer.parseInt(jLabel12.getText()),s,s2,b = Integer.parseInt(jLabel11.getText());
        
        
        
        if(nome1.equals(nome2)){
         
            jLabel6.setText("correto!");
        
            setAcertou(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/SomDeAcerto.wav")));
            getAcertou().play();
            
         s = a+1;
         jLabel12.setText(Integer.toString(s));       
            
         jButton6.setEnabled( false ); // para desabilitar um botao.
        
         if(a==9){
             
               new VoceGanhou().setVisible(true); 
               dispose(); //para fechar uma janela e abrir outra.
                getNiveis().stop();
         }
         }
        
        else{
            
            setErrou(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/SomDeErro.wav")));
            getErrou().play();
            
           s2 = b+1;
         
           if(b==9){
             
               new VocePerdeu().setVisible(true); 
               dispose(); //para fechar uma janela e abrir outra
                getNiveis().stop();
           } 
           
           else{
               
               jLabel11.setText(Integer.toString(s2)); 
               
           } 
            
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String nome1 = "docente";
        String nome2 = jTextField7.getText();
        int a = Integer.parseInt(jLabel12.getText()),s,s2,b = Integer.parseInt(jLabel11.getText());
       
        
        
        if(nome1.equals(nome2)){
         
            jLabel7.setText("correto!");
        
            setAcertou(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/SomDeAcerto.wav")));
            getAcertou().play();
            
         s = a+1;
         jLabel12.setText(Integer.toString(s));       
            
         jButton7.setEnabled( false ); // para desabilitar um botao.
        
         if(a==9){
             
               new VoceGanhou().setVisible(true); 
               dispose(); //para fechar uma janela e abrir outra.
                getNiveis().stop();
         }
         }
        
        else{
            
            setErrou(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/SomDeErro.wav")));
            getErrou().play();
            
           s2 = b+1;
         
           if(b==9){
             
               new VocePerdeu().setVisible(true); 
               dispose(); //para fechar uma janela e abrir outra
                getNiveis().stop();
           } 
           
           else{
               
               jLabel11.setText(Integer.toString(s2)); 
               
           } 
            
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String nome1 = "espécie";
        String nome2 = jTextField8.getText();
        int a = Integer.parseInt(jLabel12.getText()),s,s2,b = Integer.parseInt(jLabel11.getText());
       
        
        
        if(nome1.equals(nome2)){
         
            jLabel8.setText("correto!");
        
            setAcertou(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/SomDeAcerto.wav")));
            getAcertou().play();
            
         s = a+1;
         jLabel12.setText(Integer.toString(s));       
            
         jButton8.setEnabled( false ); // para desabilitar um botao.
        
         if(a==9){
             
               new VoceGanhou().setVisible(true); 
               dispose(); //para fechar uma janela e abrir outra.
                getNiveis().stop();
         }
         }
        
        else{
            
            setErrou(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/SomDeErro.wav")));
            getErrou().play();
            
           s2 = b+1;
         
           if(b==9){
             
               new VocePerdeu().setVisible(true); 
               dispose(); //para fechar uma janela e abrir outra
                getNiveis().stop();
           } 
           
           else{
               
               jLabel11.setText(Integer.toString(s2)); 
               
           } 
            
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String nome1 = "sucesso";
        String nome2 = jTextField9.getText();
        int a = Integer.parseInt(jLabel12.getText()),s,s2,b = Integer.parseInt(jLabel11.getText());
        
        
        
        if(nome1.equals(nome2)){
         
            jLabel9.setText("correto!");
        
            setAcertou(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/SomDeAcerto.wav")));
            getAcertou().play();
            
         s = a+1;
         jLabel12.setText(Integer.toString(s));       
            
         jButton9.setEnabled( false ); // para desabilitar um botao.
        
         if(a==9){
             
               new VoceGanhou().setVisible(true); 
               dispose(); //para fechar uma janela e abrir outra.
                getNiveis().stop();
         }
         }
        
        else{
            
            setErrou(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/SomDeErro.wav")));
            getErrou().play();
            
           s2 = b+1;
         
           if(b==9){
             
               new VocePerdeu().setVisible(true); 
               dispose(); //para fechar uma janela e abrir outra
                getNiveis().stop();
           } 
           
           else{
               
               jLabel11.setText(Integer.toString(s2)); 
               
           } 
            
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        String nome1 = "virtude";
        String nome2 = jTextField10.getText();
        int a = Integer.parseInt(jLabel12.getText()),s,s2,b = Integer.parseInt(jLabel11.getText());
        
        
        
        if(nome1.equals(nome2)){
         
            jLabel10.setText("correto!");
        
            setAcertou(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/SomDeAcerto.wav")));
            getAcertou().play();
            
         s = a+1;
         jLabel12.setText(Integer.toString(s));       
            
         jButton10.setEnabled( false ); // para desabilitar um botao.
        
         if(a==9){
             
               new VoceGanhou().setVisible(true); 
               dispose(); //para fechar uma janela e abrir outra.
                getNiveis().stop();
         }
         }
        
        else{
            
            setErrou(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/SomDeErro.wav")));
            getErrou().play();
            
           s2 = b+1;
         
           if(b==9){
             
               new VocePerdeu().setVisible(true); 
               dispose(); //para fechar uma janela e abrir outra
                getNiveis().stop();
           } 
           
           else{
               
               jLabel11.setText(Integer.toString(s2)); 
               
           } 
            
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        new LetroMania().setVisible(true);
        dispose();
        getNiveis().stop();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jLabel13AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel13AncestorAdded
        setNiveis(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/MusicaNiveis.wav")));
        getNiveis().loop();
    }//GEN-LAST:event_jLabel13AncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NivelMedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NivelMedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NivelMedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NivelMedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NivelMedio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the Acertou
     */
    public AudioClip getAcertou() {
        return Acertou;
    }

    /**
     * @param Acertou the Acertou to set
     */
    public void setAcertou(AudioClip Acertou) {
        this.Acertou = Acertou;
    }

    /**
     * @return the Errou
     */
    public AudioClip getErrou() {
        return Errou;
    }

    /**
     * @param Errou the Errou to set
     */
    public void setErrou(AudioClip Errou) {
        this.Errou = Errou;
    }

    /**
     * @return the Niveis
     */
    public AudioClip getNiveis() {
        return Niveis;
    }

    /**
     * @param Niveis the Niveis to set
     */
    public void setNiveis(AudioClip Niveis) {
        this.Niveis = Niveis;
    }
}
