/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package programa;

import java.applet.AudioClip;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author davilucas
 */
public class NivelFacil extends javax.swing.JFrame {
        private AudioClip acertou;
        private AudioClip errou;
        private AudioClip Niveis;
        
    /**
     * Creates new form NivelFacil
     */
    public NivelFacil() {
        initComponents();
        setResizable(false);
    setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(784, 542));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel1.setText("emotr");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 60, 120, 25);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel2.setText("anrec");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 120, 110, 40);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel3.setText("ezraf");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 190, 110, 20);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel4.setText("oigdn");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 250, 110, 32);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel5.setText("oumcm");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 310, 120, 29);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel6.setText("enmot");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(430, 60, 120, 29);

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel7.setText("lacuam");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(430, 130, 120, 29);

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel8.setText("rpmoi");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(430, 190, 120, 20);

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel9.setText("eargr");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(430, 250, 120, 20);

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel10.setText("snaom");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(430, 300, 120, 40);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(140, 60, 60, 26);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(140, 130, 60, 26);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(140, 190, 60, 26);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(140, 250, 60, 26);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(145, 310, 60, 26);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(534, 60, 60, 26);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(536, 130, 60, 26);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(534, 190, 60, 26);
        getContentPane().add(jTextField9);
        jTextField9.setBounds(534, 250, 60, 26);
        getContentPane().add(jTextField10);
        jTextField10.setBounds(530, 310, 60, 26);

        jButton1.setText("Verificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(210, 60, 96, 29);

        jButton2.setText("Verificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(210, 130, 96, 29);

        jButton3.setText("Verificar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(210, 190, 96, 29);

        jButton4.setText("Verificar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(210, 250, 96, 29);

        jButton5.setText("Verificar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(210, 310, 96, 29);

        jButton6.setText("Verificar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(600, 60, 96, 29);

        jButton7.setText("Verificar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(600, 130, 96, 29);

        jButton8.setText("Verificar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(600, 190, 96, 29);

        jButton9.setText("Verificar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(600, 250, 96, 29);

        jButton10.setText("Verificar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(600, 310, 96, 29);

        jLabel11.setFont(new java.awt.Font("Mistral", 1, 18)); // NOI18N
        jLabel11.setText("0");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(680, 26, 30, 20);

        jLabel12.setFont(new java.awt.Font("Mistral", 1, 18)); // NOI18N
        jLabel12.setText("0");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(280, 20, 30, 20);

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/BorrachaFinal.png"))); // NOI18N
        jButton12.setText("jButton12");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12);
        jButton12.setBounds(60, 430, 170, 70);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/NiveisFinal.gif"))); // NOI18N
        jLabel13.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jLabel13ComponentAdded(evt);
            }
        });
        jLabel13.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel13AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, -10, 790, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nome1 = "termo";
        String nome2 = jTextField2.getText();
        int a = Integer.parseInt(jLabel12.getText()),s,s2,b = Integer.parseInt(jLabel11.getText());
        
        if(nome1.equals(nome2)){
         
            jLabel1.setText("correto!");
        
            setAcertou(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/SomDeAcerto.wav")));
            getAcertou().play();
            
         s = a+1;
         jLabel12.setText(Integer.toString(s));       
            
         jButton1.setEnabled( false ); // para desabilitar um botao.
        
         if(a==9){
             
               new VoceGanhou().setVisible(true); 
               dispose(); //para fechar uma janela e abrir outra.
               getNiveis().stop();
         }
         }
        
        else{
            
            setErrou(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/SomDeErro.wav")));
            getErrou().play();
            
           s2 = b+1;
         
           if(b==9){
             
               new VocePerdeu().setVisible(true); 
               dispose(); //para fechar uma janela e abrir outra
               getNiveis().stop();
           } 
           
           else{
               
               jLabel11.setText(Integer.toString(s2)); 
               
           } 
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String nome1 = "carne";
        String nome2 = jTextField3.getText();
        int a = Integer.parseInt(jLabel12.getText()),s,s2,b = Integer.parseInt(jLabel11.getText());
        
        if(nome1.equals(nome2)){
         
            jLabel2.setText("correto!");
        
            setAcertou(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/SomDeAcerto.wav")));
            getAcertou().play();
            
         s = a+1;
         jLabel12.setText(Integer.toString(s));       
            
         jButton2.setEnabled( false ); // para desabilitar um botao.
        
         if(a==9){
             
               new VoceGanhou().setVisible(true); 
               dispose(); //para fechar uma janela e abrir outra.
               getNiveis().stop();
         }
         }
        
        else{
            
            setErrou(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/SomDeErro.wav")));
            getErrou().play();
            
           s2 = b+1;
         
           if(b==9){
             
               new VocePerdeu().setVisible(true); 
               dispose(); //para fechar uma janela e abrir outra.
               getNiveis().stop();
           } 
           
           else{
               
               jLabel11.setText(Integer.toString(s2)); 
               
           } 
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String nome1 = "fazer";
        String nome2 = jTextField4.getText();
        int a = Integer.parseInt(jLabel12.getText()),s,s2,b = Integer.parseInt(jLabel11.getText());
        
        if(nome1.equals(nome2)){
         
            jLabel3.setText("correto!");
        
            setAcertou(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/SomDeAcerto.wav")));
            getAcertou().play();
            
         s = a+1;
         jLabel12.setText(Integer.toString(s));       
            
         jButton3.setEnabled( false ); // para desabilitar um botao.
        
         if(a==9){
             
               new VoceGanhou().setVisible(true); 
               dispose(); //para fechar uma janela e abrir outra.
               getNiveis().stop();
         }
         }
        
        else{
            
            setErrou(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/SomDeErro.wav")));
            getErrou().play();
            
           s2 = b+1;
         
           if(b==9){
             
               new VocePerdeu().setVisible(true); 
               dispose(); //para fechar uma janela e abrir outra.
               getNiveis().stop();
           } 
           
           else{
               
               jLabel11.setText(Integer.toString(s2)); 
               
           } 
            
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String nome1 = "digno";
        String nome2 = jTextField1.getText();
        int a = Integer.parseInt(jLabel12.getText()),s,s2,b = Integer.parseInt(jLabel11.getText());
        
        if(nome1.equals(nome2)){
         
            jLabel4.setText("correto!");
        
            setAcertou(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/SomDeAcerto.wav")));
            getAcertou().play();
            
         s = a+1;
         jLabel12.setText(Integer.toString(s));       
            
         jButton4.setEnabled( false ); // para desabilitar um botao.
        
         if(a==9){
             
               new VoceGanhou().setVisible(true); 
               dispose(); //para fechar uma janela e abrir outra.
               getNiveis().stop();
         }
         }
        
        else{
            
           setErrou(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/SomDeErro.wav")));
            getErrou().play();
            
           s2 = b+1;
         
           if(b==9){
             
               new VocePerdeu().setVisible(true); 
               dispose(); //para fechar uma janela e abrir outra.
               getNiveis().stop();
           } 
           
           else{
               
               jLabel11.setText(Integer.toString(s2)); 
               
           } 
            
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String nome1 = "comum";
        String nome2 = jTextField5.getText();
        int a = Integer.parseInt(jLabel12.getText()),s,s2,b = Integer.parseInt(jLabel11.getText());
        
        if(nome1.equals(nome2)){
         
            jLabel5.setText("correto!");
        
            setAcertou(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/SomDeAcerto.wav")));
            getAcertou().play();
            
         s = a+1;
         jLabel12.setText(Integer.toString(s));       
            
         jButton5.setEnabled( false ); // para desabilitar um botao.
        
         if(a==9){
             
               new VoceGanhou().setVisible(true); 
               dispose(); //para fechar uma janela e abrir outra.
               getNiveis().stop();
         }
         }
        
        else{
            
            setErrou(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/SomDeErro.wav")));
            getErrou().play();
            
           s2 = b+1;
         
           if(b==9){
             
               new VocePerdeu().setVisible(true); 
               dispose(); //para fechar uma janela e abrir outra.
               getNiveis().stop();
           } 
           
           else{
               
               jLabel11.setText(Integer.toString(s2)); 
               
           } 
            
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String nome1 = "ontem";
        String nome2 = jTextField6.getText();
        int a = Integer.parseInt(jLabel12.getText()),s,s2,b = Integer.parseInt(jLabel11.getText());
        
        if(nome1.equals(nome2)){
         
            jLabel6.setText("correto!");
        
            setAcertou(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/SomDeAcerto.wav")));
            getAcertou().play();
            
         s = a+1;
         jLabel12.setText(Integer.toString(s));       
            
         jButton6.setEnabled( false ); // para desabilitar um botao.
        
         if(a==9){
             
               new VoceGanhou().setVisible(true); 
               dispose(); //para fechar uma janela e abrir outra.
               getNiveis().stop();
         }
         }
        
        else{
           
            setErrou(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/SomDeErro.wav")));
            getErrou().play();
            
           s2 = b+1;
         
           if(b==9){
             
               new VocePerdeu().setVisible(true); 
               dispose(); //para fechar uma janela e abrir outra.
               getNiveis().stop();
           } 
           
           else{
               
               jLabel11.setText(Integer.toString(s2)); 
               
           } 
            
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String nome1 = "maluca";
        String nome2 = jTextField7.getText();
        int a = Integer.parseInt(jLabel12.getText()),s,s2,b = Integer.parseInt(jLabel11.getText());
        
        if(nome1.equals(nome2)){
         
            jLabel7.setText("correto!");
        
            setAcertou(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/SomDeAcerto.wav")));
            getAcertou().play();
            
         s = a+1;
         jLabel12.setText(Integer.toString(s));       
            
         jButton7.setEnabled( false ); // para desabilitar um botao.
        
         if(a==9){
             
               new VoceGanhou().setVisible(true); 
               dispose(); //para fechar uma janela e abrir outra.
               getNiveis().stop();
         }
         }
        
        else{
           
            setErrou(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/SomDeErro.wav")));
            getErrou().play();
            
           s2 = b+1;
         
           if(b==9){
             
               new VocePerdeu().setVisible(true); 
               dispose(); //para fechar uma janela e abrir outra.
               getNiveis().stop();
           } 
           
           else{
               
               jLabel11.setText(Integer.toString(s2)); 
               
           } 
            
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String nome1 = "impor";
        String nome2 = jTextField8.getText();
        int a = Integer.parseInt(jLabel12.getText()),s,s2,b = Integer.parseInt(jLabel11.getText());
        
        if(nome1.equals(nome2)){
         
            jLabel8.setText("correto!");
        
            setAcertou(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/SomDeAcerto.wav")));
            getAcertou().play();
            
         s = a+1;
         jLabel12.setText(Integer.toString(s));       
            
         jButton8.setEnabled( false ); // para desabilitar um botao.
        
         if(a==9){
             
               new VoceGanhou().setVisible(true); 
               dispose(); //para fechar uma janela e abrir outra.
               getNiveis().stop();
         }
         }
        
        else{
            
            setErrou(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/SomDeErro.wav")));
            getErrou().play();
            
           s2 = b+1;
         
           if(b==9){
             
               new VocePerdeu().setVisible(true); 
               dispose(); //para fechar uma janela e abrir outra.
               getNiveis().stop();
           } 
           
           else{
               
               jLabel11.setText(Integer.toString(s2)); 
               
           } 
            
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String nome1 = "regra";
        String nome2 = jTextField9.getText();
        int a = Integer.parseInt(jLabel12.getText()),s,s2,b = Integer.parseInt(jLabel11.getText());
        
        if(nome1.equals(nome2)){
         
            jLabel9.setText("correto!");
        
            setAcertou(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/SomDeAcerto.wav")));
            getAcertou().play();
            
         s = a+1;
         jLabel12.setText(Integer.toString(s));       
            
         jButton9.setEnabled( false ); // para desabilitar um botao.
        
         if(a==9){
             
               new VoceGanhou().setVisible(true); 
               dispose(); //para fechar uma janela e abrir outra.
               getNiveis().stop();
         }
         }
        
        else{
            
            setErrou(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/SomDeErro.wav")));
            getErrou().play();
            
           s2 = b+1;
         
           if(b==9){
             
               new VocePerdeu().setVisible(true); 
               dispose(); //para fechar uma janela e abrir outra.
               getNiveis().stop();
           } 
           
           else{
               
               jLabel11.setText(Integer.toString(s2)); 
               
           } 
            
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        String nome1 = "manso";
        String nome2 = jTextField10.getText();
        int a = Integer.parseInt(jLabel12.getText()),s,s2,b = Integer.parseInt(jLabel11.getText());
        
        if(nome1.equals(nome2)){
         
            jLabel10.setText("correto!");
        
            setAcertou(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/SomDeAcerto.wav")));
            getAcertou().play();
            
         s = a+1;
         jLabel12.setText(Integer.toString(s));       
            
         jButton10.setEnabled( false ); // para desabilitar um botao.
        
         if(a==9){
             
               new VoceGanhou().setVisible(true); 
               dispose(); //para fechar uma janela e abrir outra.
               getNiveis().stop();
         }
         }
        
        else{
            
            setErrou(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/SomDeErro.wav")));
            getErrou().play();
            
           s2 = b+1;
         
           if(b==9){
             
               new VocePerdeu().setVisible(true); 
               dispose(); //para fechar uma janela e abrir outra.
               getNiveis().stop();
           } 
           
           else{
               
               jLabel11.setText(Integer.toString(s2)); 
               
           } 
            
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        new LetroMania().setVisible(true);
        dispose();
        getNiveis().stop();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jLabel13ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jLabel13ComponentAdded
      
    }//GEN-LAST:event_jLabel13ComponentAdded

    private void jLabel13AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel13AncestorAdded
        
        setNiveis(java.applet.Applet.newAudioClip(getClass().getResource("/musicas/MusicaNiveis.wav")));
        getNiveis().loop();
    }//GEN-LAST:event_jLabel13AncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NivelFacil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NivelFacil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NivelFacil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NivelFacil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NivelFacil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the acertou
     */
    public AudioClip getAcertou() {
        return acertou;
    }

    /**
     * @param acertou the acertou to set
     */
    public void setAcertou(AudioClip acertou) {
        this.acertou = acertou;
    }

    /**
     * @return the errou
     */
    public AudioClip getErrou() {
        return errou;
    }

    /**
     * @param errou the errou to set
     */
    public void setErrou(AudioClip errou) {
        this.errou = errou;
    }

    /**
     * @return the Niveis
     */
    public AudioClip getNiveis() {
        return Niveis;
    }

    /**
     * @param Niveis the Niveis to set
     */
    public void setNiveis(AudioClip Niveis) {
        this.Niveis = Niveis;
    }

   
}
